# Magnum CI: Hosted Continuous Integration Platform
# https://magnum-ci.com

#before_install:

install:
  - echo "do not install anything yet"

#before_script:

script:
  - sh tests/test-suite.sh

#after_script:
