# Magnum CI: Hosted Continuous Integration Platform
# https://magnum-ci.com

#before_install:

install:
  # require PHP command line
  - sudo apt-get update --yes --quiet
  - sudo apt-get install --yes --quiet php5-cli

#before_script:

script:
  - sh tests/test-suite.sh

#after_script:
