# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

branches:
    only:
        - master
        - develop

env:
    global:
        - COMPOSER_CACHE_DIR=.composer-cache/

script: ./tests/test-suite.sh
